# Site settings
title:          푸글로그
description:    "성장하는 개발자"
baseurl:        ""
url:            "https://suhyunsim.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Suhyun Sim
  url:          https://suhyunsim.github.io
  email:        pcn021152@gmail.com

navigation:
  - name: Blog
    url: /
  - name: About
    url: /about
  - name: Tags
    url: /tags  


# Includes an icon in the footer for each username you enter
footer-links:
#  dribbble:
  email: pcn021152@gmail.com
  facebook: facebook.com/suhyunssimm
#  flickr:
  github: github.com/suhyunsim
#  instagram: 
#  linkedin:
#  pinterest:
  rss: # just type anything here for a working RSS icon
#  twitter: 
#  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
#  youtube: # channel/<your_long_string> or user/<user-name>
#  googleplus: # anything in your profile username that comes after plus.google.com/


# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         suhyunsim-github-io

category_dir: categories/
category_list: [ Project, BackEnd, Algorithm, TIL, Others]

tag_dir: tags/

# #Scripts
# search: true